networks:
  ollama-docker:
    external: false

services:
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest-alpine
    container_name: oauth2-proxy
    command:
      - --http-address
      - 0.0.0.0:4180
    environment:
      OAUTH2_PROXY_CLIENT_ID: ${OAUTH2_PROXY_CLIENT_ID}
      OAUTH2_PROXY_CLIENT_SECRET: ${OAUTH2_PROXY_CLIENT_SECRET}
      OAUTH2_PROXY_COOKIE_REFRESH: 30m
      OAUTH2_PROXY_COOKIE_SECRET: ${OAUTH2_PROXY_COOKIE_SECRET}
      OAUTH2_PROXY_EMAIL_DOMAINS: '*'
      OAUTH2_PROXY_PROVIDER: github
      OAUTH2_PROXY_PROVIDER_DISPLAY_NAME: GitHub
      OAUTH2_PROXY_REDIRECT_URL: https://${YOUR_ANIMAL}.llmcloud24.bihealth.org/oauth2/callback
      OAUTH2_PROXY_COOKIE_SECURE: "true" # Disable secure cookies if not using HTTPS
      OAUTH2_PROXY_SET_XAUTHREQUEST: "true"
      OAUTH2_PROXY_PASS_USER_HEADERS: "true"
      OAUTH2_PROXY_PASS_ACCESS_TOKEN: "true"
    ports:
      - 4180:4180
    #networks:
    #  - ollama-docker
    #needed for this to talk to github from inside
    network_mode: "host"

  ollama-nginx:
    image: nginx:latest
    container_name: ollama-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - oauth2-proxy
      - ollama-webui
    ports:
      - 80:80
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - ollama-docker

  ollama-webui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: ollama-webui
    volumes:
      - ./ollama/ollama-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 8080:8080
    environment: # https://docs.openwebui.com/getting-started/env-configuration#default_models
      - OLLAMA_BASE_URLS=http://10.0.2.137:7869 #comma separated ollama hosts
      - ENV=prod
      - WEBUI_AUTH=False
      - WEBUI_URL=http://localhost:8080
      - WEBUI_SECRET_KEY=<secret>
      - ENABLE_OAUTH_SIGNUP=true
      - DEFAULT_USER_ROLE=user
      - OAUTH_MERGE_ACCOUNTS_BY_EMAIL=true
      - WEBUI_AUTH_TRUSTED_EMAIL_HEADER=X-Forwarded-Email
      - WEBUI_AUTH_TRUSTED_NAME_HEADER=X-Forwarded-User
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      - ollama-docker